name: PocketDimension
version: 2.0
main: com.example.pocketdimension.PocketPlugin
api-version: 1.18
description: A virtual pocket dimension to store and withdraw building blocks
author: Calvin

commands:
  pocket:
    description: Gives the player a Dimensional Pocket
    usage: /pocket
  pocketleaderboard:
    description: Shows the leaderboard of the most used blocks
    usage: /pocketleaderboard

permissions:
  pocketdimension.use:
    description: Allows the player to use /pocket
    default: true
  pocketdimension.leaderboard:
    description: Allows the player to use /pocketleaderboard
    default: true
  pocketdimension.reload:
    description: Allows reloading the pocket GUI without a server restart
    default: op